Modified the login form to match Zepelin's specification. Modified CS…
pokt-network/pocket-dashboard pull request #105
Opened 2020-05-27 17:15 UTC by arturoruiz

…S properties to match the styling.

2020-05-27 17:22 UTC, xerp requested changes

2020-05-27 17:22 UTC, xerp commented on frontend/src/core/components/AuthSidebar/AuthSidebar.scss
> +    font-family: OpenSans;
About this properties like font we have a scss file, that has font properties, please import that file(Variables/Font.scss) and use it here.

2020-05-27 17:22 UTC, xerp commented on frontend/src/core/components/AuthSidebar/AuthSidebar.scss
> +    font-family: Lato;
About this properties like font we have a scss file, that has font properties, please import that file(Variables/Font.scss) and use it here.

2020-05-27 17:22 UTC, xerp commented on frontend/src/views/Auth/Login/Login.scss
> +  font-family: OpenSans;
About this properties like font we have a scss file, that has font properties, please import that file(Variables/Font.scss) and use it here.

2020-05-27 22:26 UTC, rafaeldeleonp approved these changes

2020-05-27 22:26 UTC, rafaeldeleonp commented on frontend/src/views/Auth/Login/Login.scss
> +  width: 93px;
Remove this styles. This is being applied to every h2. If you log in and get to the home (Network Status) you will that all h2 titles, the text will be two lines.

2020-05-28 12:36 UTC, xerp approved these changes

2020-05-28 12:40 UTC, merged