Style select tokens views
pokt-network/pocket-dashboard pull request #133
Opened 2020-05-30 02:25 UTC by justaname94

2020-05-30 02:39 UTC, xerp approved these changes

2020-05-30 02:48 UTC, xerp submitted a review, later dismissed
This PR has issues on functionality.

2020-05-30 21:01 UTC, xerp requested changes

2020-05-30 21:01 UTC, xerp commented on frontend/src/core/components/AppOrderSummary/AppOrderSummary.js
> +          <Form.Control value={balance} onChange={balanceOnChange} readOnly />
@justaname94 The user needs edit the value, to adjust the amount to checkout, so, this field cannot be read only.

2020-06-01 19:02 UTC, xerp approved these changes

2020-06-01 20:51 UTC, rafaeldeleonp approved these changes

2020-06-01 21:19 UTC, merged