Issue #196
pokt-network/pocket-dashboard pull request #217
Opened 2020-07-21 00:37 UTC by pabelnl

Closes #196

2020-07-21 00:40 UTC, nymd requested changes

2020-07-21 00:40 UTC, nymd commented on backend/src/models/Application.js
> +    let { freeTierApplicationAccount } = applicationData
Push will fail without linting, pls see warnings/failures

2020-07-21 00:40 UTC, nymd commented on backend/src/services/ApplicationService.js
> +    return extendedPocketApplication
requires ;

2020-07-21 16:18 UTC, wgarcia4190 submitted a review, later dismissed

2020-07-21 23:45 UTC, nymd submitted a review, later dismissed

2020-07-22 00:23 UTC, nymd approved these changes

2020-07-22 00:29 UTC, wgarcia4190 approved these changes

2020-07-22 00:36 UTC, merged