Issues #191
pokt-network/pocket-dashboard pull request #242
Opened 2020-07-27 17:48 UTC by pabelnl

Closes #237 #236 #232

2020-07-27 17:49 UTC, wgarcia4190 submitted a review, later dismissed

2020-07-27 21:28 UTC, nymd requested changes

2020-07-27 21:28 UTC, nymd commented on backend/src/apis/UserApi.js
> +    res.send(false);
We should not indicate whether or not the user exists in our database.

It should look like the password reset email was sent even if the user DOES NOT exist in our database.  This prevents the system from leaking information about what users are registered.

2020-07-27 21:28 UTC, nymd commented on frontend/src/views/Auth/AnswerSecurityQuestions/AnswerSecurityQuestions.js
> +      ]
linting please

2020-07-29 17:07 UTC, nymd approved these changes

2020-07-29 17:08 UTC, wgarcia4190 approved these changes

2020-07-29 17:10 UTC, merged