Updating Node form
pokt-network/pocket-dashboard pull request #244
Opened 2020-07-30 16:20 UTC by wgarcia4190

Close #230

2020-07-30 17:53 UTC, pabelnl requested changes

2020-07-30 17:53 UTC, pabelnl commented on frontend/src/views/Nodes/CreateNodeForm/CreateNodeForm.js
> +      agreeTerms: true,
why the agree terms checkbox is true from the beginning?

2020-07-30 20:01 UTC, pabelnl approved these changes

2020-07-31 14:40 UTC, luyzdeleon approved these changes

2020-07-31 14:40 UTC, merged