Issue #228
pokt-network/pocket-dashboard pull request #251
Opened 2020-07-31 17:31 UTC by wgarcia4190

2020-07-31 17:45 UTC, pabelnl submitted a review, later dismissed

2020-08-01 17:35 UTC, nymd requested changes

2020-08-01 17:35 UTC, nymd commented on frontend/src/views/Nodes/CreateNodeForm/CreateNodeForm.js
> +                        <Form.Label>Write an optional descriptio of your app here</Form.Label>
Missing n on description

2020-08-01 17:35 UTC, nymd commented on frontend/src/views/Nodes/NodeChainList/NodeChainList.js
>            </Col>
Choose the chains that your Pocket Node will service. Your staked POKT will be evenly divided between these selections. You will not be able to change this selection unless you unstake and restake your node.

2020-08-01 17:35 UTC, nymd commented on frontend/src/views/Nodes/NodeChainList/NodeChainList.js
> +                      Please provide the endpoint HTTPS of your node. <a href="https://docs.pokt.network/docs/faq-for-nodes#section-what-is-the-service-uri">What is the service URL?</a>
Please provide the HTTPS endpoint of your Pocket Node.

2020-08-01 17:35 UTC, nymd commented on frontend/src/views/Nodes/NodeChainList/NodeChainList.js
> +                              WARNING, BEFORE YOU CONTINUE!!{" "}
Only one! Please

2020-08-01 17:35 UTC, nymd commented on frontend/src/views/Nodes/NodeChainList/NodeChainList.js
> +                Before continue, be aware that we are not responsible of any jailing or slashing that may incur due to mis-configuration of your node. If you are not completely sure if your node is c
Before continuing...

2020-08-01 20:00 UTC, pabelnl approved these changes

2020-08-01 20:10 UTC, nymd approved these changes

2020-08-01 20:59 UTC, merged