Create forgot password view
pokt-network/pocket-dashboard pull request #3
Opened 2020-03-17 16:22 UTC by justaname94

2020-03-18 02:10 UTC, xerp requested changes
@justaname94 Please check the comments on changes in this PR.

2020-03-18 02:10 UTC, xerp commented on frontend/src/views/Core/ForgotPassword/ForgotPassword.js
> +            <div className={"help"}>
We need to create a Help component, please create one and reuse here and the Login Page.
Create this component inside core/components.

2020-03-18 02:10 UTC, xerp commented on frontend/src/views/Core/ForgotPassword/ForgotPassword.scss
> +  #navbar {
As you said, please create a **sidebar** component and move the css of these components to **Core** scss
Create the sidebar inside _core/components_ for the js and for css move to _scss/Core.scss_.

2020-03-18 02:10 UTC, xerp commented on frontend/src/views/Core/ForgotPassword/ForgotPassword.scss
> +@import "src/scss/Core";
In the css of each component page, _we need only the css for the page component_, for general components we need the logic on Core.scss

2020-03-18 02:10 UTC, xerp commented on frontend/src/_routes.js
> +export const FORGOTPASSWORD_PATH = "/forgot-password";
For these ones, please refactoring to a JSON variable named routePaths, with the following structure:

```javascript
export const routePaths = {
login: "/login",
home: "/home",
forgot_password: "/forgot-password"
.
.
.
};
```
Then change all old references for the new ones.

2020-03-18 02:20 UTC, xerp commented
Also for our conversation, we need a naming convention for branch, we will use the following prefixes:

- For **features**: _feature/[frontend|backend], feature/[frontend|backend]/[page|component]_
- For **bugs**: _bugfix/[frontend|backend], bugfix/[frontend|backend]/[page|component]_

Examples:

1. We need to create app page, the branch name will be: feature/frontend/page/app.
2. We need to resolve an issue about balance on backend pokt service, the branch name will be: bugfix/backend/[name]

2020-03-18 02:24 UTC, justaname94 commented
All right, I'll be applying them tomorrow morning

2020-03-18 16:15 UTC, xerp requested changes

2020-03-18 16:15 UTC, xerp commented on frontend/src/core/components/Help/Help.js
> +export default Help;
For component, we need to follow class based component style.
Please use _core/components/AuthProviderButton.js_ as example.

Also use propTypes property of component if is needed.

2020-03-19 13:01 UTC, xerp commented
Looks good

2020-03-19 13:01 UTC, merged