Issue-#331
pokt-network/pocket-dashboard pull request #333
Opened 2020-08-06 19:52 UTC by pabelnl

Closes #331 #332

2020-08-06 20:35 UTC, nymd requested changes

2020-08-06 20:35 UTC, nymd commented on backend/src/services/ApplicationService.js
>          version: gatewayAAT.version,
typo here: should be aat.

or change it to freeTierAAT to make it more clear

2020-08-07 14:22 UTC, nymd approved these changes

2020-08-07 14:56 UTC, wgarcia4190 approved these changes

2020-08-07 15:36 UTC, merged